import psycopg2
import json
from datetime import datetime as dt

# --- Database Interaction Functions ---

def insert_patient(cur, data):
    """Inserts or updates a patient record and returns the patient's PK uuid."""
    application_uuid_from_json = data.get("uuid") 
    if not application_uuid_from_json:
        raise ValueError("Application UUID (from JSON 'uuid' field) is missing but required.")

    cur.execute("""
        INSERT INTO treatment_chart.patient (uhid, name, age_in_months, age_in_years, sex, application_uuid)
        VALUES (%s, %s, %s, %s, %s, %s)
        ON CONFLICT (uhid) DO UPDATE SET
            name = EXCLUDED.name,
            age_in_months = EXCLUDED.age_in_months,
            age_in_years = EXCLUDED.age_in_years,
            sex = EXCLUDED.sex,
            application_uuid = EXCLUDED.application_uuid
        RETURNING uuid;
    """, (
        data.get("uhid"),
        data.get("Name"),
        data.get("Age_month"),
        data.get("Age_year"),
        data.get("Sex"),
        application_uuid_from_json
    ))
    patient_pk_uuid = cur.fetchone()[0] 
    print(f"Patient PK (DB-generated or existing): {patient_pk_uuid} (App UUID from JSON: {application_uuid_from_json})")
    return patient_pk_uuid

def insert_diagnosis(cur, data, fk_patient_uuid):
    """
    Inserts a diagnosis record and returns its diagnosis_id (PK).
    """
    diagnosis_text = data.get("Diagnosis") or data.get("diagnosis") or "N/A"
    cur.execute("""
        INSERT INTO treatment_chart.diagnosis (patient_uuid, diagnosis_text, consultants, jr, sr)
        VALUES (%s, %s, %s, %s, %s)
        RETURNING diagnosis_id;
    """, (
        fk_patient_uuid, 
        diagnosis_text,
        data.get("Consultants") or data.get("consultants"),
        data.get("JR") or data.get("jr"),
        data.get("SR") or data.get("sr")
    ))
    diagnosis_pk_id = cur.fetchone()[0]
    print(f"Diagnosis PK (DB-generated): {diagnosis_pk_id}, linked to Patient PK: {fk_patient_uuid}")
    return diagnosis_pk_id


def insert_observation(cur, data, fk_diagnosis_id, each_table_row_layout_data):
    """
    Inserts an observation record and returns its observation_id (PK).
    prescription_date and prescription_time are extracted from each_table_row_layout's 'row_header_description'.
    Other metrics are also extracted from each_table_row_layout's 'row_header_description'.
    The entire `each_table_row_layout_data` is stored as JSON in the `extra_metric` column.
    created_at is auto-generated by the DB.
    """
    prescription_date_val = None
    prescription_time_val = None
    weight_val = None
    length_val = None
    bsa_val = None
    tfr_val = None
    tfv_val = None
    ivm_val = None
    ivf_val = None
    feeds_val = None
    gir_mg_kg_min_val = None
    k_plus_val = None
    egfr_val = None

    if each_table_row_layout_data:
        for row_key, row_details in each_table_row_layout_data.items():
            header_name = row_details.get("row_header_name", "").strip().lower()
            value_from_description = row_details.get("row_header_description", "").strip()

            if value_from_description: 
                if header_name == "date":
                    prescription_date_val = value_from_description
                elif header_name == "time":
                    prescription_time_val = value_from_description
                elif header_name == "weight":
                    weight_val = value_from_description
                elif header_name == "length":
                    length_val = value_from_description
                elif header_name == "bsa":
                    bsa_val = value_from_description
                elif header_name == "tfr":
                    tfr_val = value_from_description
                elif header_name == "tfv":
                    tfv_val = value_from_description
                elif header_name == "ivm":
                    ivm_val = value_from_description
                elif header_name == "ivf":
                    ivf_val = value_from_description
                elif header_name == "feeds":
                    feeds_val = value_from_description
                elif header_name == "gir(mg/kg/min)":
                    gir_mg_kg_min_val = value_from_description
                elif header_name == "k+":
                    k_plus_val = value_from_description
                elif header_name == "egfr":
                    egfr_val = value_from_description

    if prescription_date_val is None:
        prescription_date_val = "N/A" 
        print("Warning: Prescription Date not found or empty in each_table_row_layout. Using default 'N/A'.")
    if prescription_time_val is None:
        prescription_time_val = "N/A" 
        print("Warning: Prescription Time not found or empty in each_table_row_layout. Using default 'N/A'.")

    extra_metric_json_content = None
    if each_table_row_layout_data: 
        try:
            extra_metric_json_content = json.dumps(each_table_row_layout_data)
        except TypeError as te:
            print(f"Warning: Could not serialize each_table_row_layout_data to JSON for extra_metric: {te}. Storing NULL.")
    else:
        print("Warning: `each_table_row_layout_data` is empty or None. `extra_metric` will be stored as NULL (or empty JSON if column requires it).")

    cur.execute("""
        INSERT INTO treatment_chart.observation (
            diagnosis_id, prescription_date, prescription_time,
            weight, length, bsa, tfr, tfv, ivm, ivf,
            feeds, gir_mg_kg_min, k_plus, egfr, extra_metric
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        RETURNING observation_id, created_at;
    """, (
        fk_diagnosis_id, prescription_date_val, prescription_time_val,
        weight_val, length_val, bsa_val, tfr_val, tfv_val, ivm_val, ivf_val,
        feeds_val, gir_mg_kg_min_val, k_plus_val, egfr_val, 
        extra_metric_json_content 
    ))
    result = cur.fetchone()
    observation_pk_id = result[0]
    created_at_timestamp = result[1]
    print(f"Observation PK (DB-generated): {observation_pk_id}, Created At (DB): {created_at_timestamp}")
    print(f"  Prescription Date: {prescription_date_val}, Prescription Time: {prescription_time_val}")
    if extra_metric_json_content:
        print(f"  Stored `each_table_row_layout_data` as JSON in observation.extra_metric.")
    else:
        print(f"  `observation.extra_metric` stored as NULL (or default empty JSON).")
    return observation_pk_id

def insert_extra_table_layouts(cur, data, fk_observation_id):
    """
    Archives ONLY the original `each_entry_layout` into the extra_table.
    """
    each_entry_layout_data = data.get("each_entry_layout") 
    
    if each_entry_layout_data: 
        try:
            json_content_for_extra_table = json.dumps(each_entry_layout_data)
            cur.execute("""
                INSERT INTO treatment_chart.extra_table (observation_id, json_content)
                VALUES (%s, %s);
            """, (fk_observation_id, json_content_for_extra_table))
            print(f"Stored `each_entry_layout` in extra_table for Observation PK: {fk_observation_id}")
        except TypeError as te:
            print(f"Error serializing `each_entry_layout` to JSON for extra_table: {te}")
    else:
        print(f"`each_entry_layout` not found or empty. No record inserted into extra_table.")


# --- Detail Table Insertion Functions ---
def insert_respiratory_support(cur, fk_observation_id, subtitle_data):
    content = subtitle_data.get("content","").strip()
    if not content: return
    print(f"\n=== Inserting Respiratory Support ===")
    print(f"Content: {content}")
    print(f"Rate: {subtitle_data.get('rate')}")
    print(f"Volume: {subtitle_data.get('volume')}")
    cur.execute("INSERT INTO treatment_chart.respiratory_support (observation_id, content, rate, volume) VALUES (%s, %s, %s, %s);",
                (fk_observation_id, content, subtitle_data.get("rate"), subtitle_data.get("volume")))
    print("✓ Respiratory support record saved")

def insert_sedation(cur, fk_observation_id, subtitle_data):
    content = subtitle_data.get("content","").strip()
    if not content: return
    print(f"\n=== Inserting Sedation ===")
    print(f"Content: {content}")
    print(f"Dose: {subtitle_data.get('dose')}")
    print(f"Volume: {subtitle_data.get('volume')}")
    cur.execute("INSERT INTO treatment_chart.sedation (observation_id, content, dose, volume) VALUES (%s, %s, %s, %s);",
                (fk_observation_id, content, subtitle_data.get("dose"), subtitle_data.get("volume")))
    print("✓ Sedation record saved")

def insert_inotropes(cur, fk_observation_id, subtitle_data):
    content = subtitle_data.get("content","").strip()
    if not content: return
    print(f"\n=== Inserting Inotropes ===")
    print(f"Content: {content}")
    print(f"Dose: {subtitle_data.get('dose')}")
    print(f"Volume: {subtitle_data.get('volume')}")
    cur.execute("INSERT INTO treatment_chart.inotropes (observation_id, content, dose, volume) VALUES (%s, %s, %s, %s);",
                (fk_observation_id, content, subtitle_data.get("dose"), subtitle_data.get("volume")))
    print("✓ Inotropes record saved")

def insert_antimicrobials(cur, fk_observation_id, subtitle_data):
    content = subtitle_data.get("content","").strip()
    if not content: return
    print(f"\n=== Inserting Antimicrobials ===")
    print(f"Content: {content}")
    print(f"Day: {subtitle_data.get('day')}")
    print(f"Dose: {subtitle_data.get('dose')}")
    print(f"Volume: {subtitle_data.get('volume')}")
    cur.execute("INSERT INTO treatment_chart.antimicrobials (observation_id, content, day, dose, volume) VALUES (%s, %s, %s, %s, %s);",
                (fk_observation_id, content, subtitle_data.get("day"), subtitle_data.get("dose"), subtitle_data.get("volume")))
    print("✓ Antimicrobials record saved")

def insert_iv_fluid(cur, fk_observation_id, subtitle_data):
    content = subtitle_data.get("content","").strip()
    if not content: return
    print(f"\n=== Inserting IV Fluid ===")
    print(f"Content: {content}")
    print(f"Rate: {subtitle_data.get('rate')}")
    print(f"Volume: {subtitle_data.get('volume')}")
    cur.execute("INSERT INTO treatment_chart.iv_fluid (observation_id, content, rate, volume) VALUES (%s, %s, %s, %s);",
                (fk_observation_id, content, subtitle_data.get("rate"), subtitle_data.get("volume")))
    print("✓ IV fluid record saved")

def insert_feeds(cur, fk_observation_id, subtitle_data):
    content = subtitle_data.get("content","").strip()
    if not content: return
    print(f"\n=== Inserting Feeds ===")
    print(f"Content: {content}")
    print(f"Volume: {subtitle_data.get('volume')}")
    cur.execute("INSERT INTO treatment_chart.feeds (observation_id, content, volume) VALUES (%s, %s, %s);",
                (fk_observation_id, content, subtitle_data.get("volume")))
    print("✓ Feeds record saved")

def insert_other_medications(cur, fk_observation_id, subtitle_data):
    content = subtitle_data.get("content","").strip()
    if not content: return
    print(f"\n=== Inserting Other Medications ===")
    print(f"Content: {content}")
    print(f"Dose: {subtitle_data.get('dose')}")
    print(f"Volume: {subtitle_data.get('volume')}")
    cur.execute("INSERT INTO treatment_chart.other_medications (observation_id, content, dose, volume) VALUES (%s, %s, %s, %s);",
                (fk_observation_id, content, subtitle_data.get("dose"), subtitle_data.get("volume")))
    print("✓ Other medications record saved")

# --- NEW FUNCTION ---
def insert_supportive_care(cur, fk_observation_id, subtitle_data):
    """Inserts a supportive care record."""
    content = subtitle_data.get("content","").strip()
    if not content: return # Do not insert if content is empty
    
    print(f"\n=== Inserting Supportive Care ===")
    print(f"Content: {content}")
    print(f"Rate: {subtitle_data.get('rate')}")       # As per table schema
    print(f"Volume: {subtitle_data.get('volume')}")   # As per table schema
    
    cur.execute("""
        INSERT INTO treatment_chart.supportive_care (observation_id, content, rate, volume) 
        VALUES (%s, %s, %s, %s);
    """,(
        fk_observation_id, 
        content, 
        subtitle_data.get("rate"),      # Will be NULL if not in JSON
        subtitle_data.get("volume")     # Will be NULL if not in JSON
    ))
    print("✓ Supportive care record saved")
# --- END NEW FUNCTION ---


# --- Main Processing Logic ---
def process_json_data(json_input_str_or_dict):
    if isinstance(json_input_str_or_dict, str):
        data = json.loads(json_input_str_or_dict)
    elif isinstance(json_input_str_or_dict, dict):
        data = json_input_str_or_dict
    else:
        raise TypeError("Input must be a JSON string or a Python dictionary.")

    print("\n=== Input Data Structure ===")
    print("Keys in input data:", list(data.keys()))
    
    if "parameters" in data and "each_table_row_layout" not in data:
        print("\n=== Transforming parameters to each_table_row_layout ===")
        data["each_table_row_layout"] = data.pop("parameters")
        print("Transformed parameters to each_table_row_layout")
        print("New keys:", list(data.keys()))
    
    if "entries" in data and "each_entry_layout" not in data:
        print("\n=== Transforming entries to each_entry_layout ===")
        data["each_entry_layout"] = data.pop("entries")
        print("Transformed entries to each_entry_layout")
        print("New keys:", list(data.keys()))

    db_params = {
        "dbname": "mydb",
        "user": "admin",
        "password": "admin",
        "host": "treatment_chart_db", # Changed for Docker internal networking
        "port": "5432"
    }

    print("\n=== PostgreSQL Connection Parameters ===")
    print(f"Database: {db_params['dbname']}")
    print(f"Host: {db_params['host']}")
    print(f"Port: {db_params['port']}")
    print(f"User: {db_params['user']}")

    conn = None
    cur = None

    try:
        print("\n=== Attempting Database Connection ===")
        conn = psycopg2.connect(**db_params)
        cur = conn.cursor()
        print("✓ Successfully connected to PostgreSQL database")

        print("\n=== Starting Data Insertion Process ===")
        print("1. Inserting/Updating Patient Record...")
        patient_pk_uuid = insert_patient(cur, data)
        print(f"✓ Patient record processed with UUID: {patient_pk_uuid}")

        print("\n2. Inserting Diagnosis Record...")
        diagnosis_pk_id = insert_diagnosis(cur, data, patient_pk_uuid)
        print(f"✓ Diagnosis record created with ID: {diagnosis_pk_id}")

        each_entry_layout_data = data.get("each_entry_layout", {}) 
        each_table_row_layout_data = data.get("each_table_row_layout", {})
        
        print("\n3. Inserting Observation Record...")
        observation_pk_id = insert_observation(cur, data, diagnosis_pk_id,
                                               each_table_row_layout_data)
        print(f"✓ Observation record created with ID: {observation_pk_id}")

        print("\n4. Archiving `each_entry_layout` Data (into extra_table)...")
        insert_extra_table_layouts(cur, data, observation_pk_id) 

        if each_entry_layout_data: 
            print("\n5. Processing Treatment Details...")
            treatment_count = 0
            for entry_key, entry_value in each_entry_layout_data.items():
                title = entry_value.get("title", "").strip().lower()
                subtitles_dict = entry_value.get("subtitles")
                if not subtitles_dict:
                    continue
                
                subtitle_data = subtitles_dict.get("subtitle_1", {})
                if not subtitle_data: 
                    continue
                
                print(f"\n   Processing treatment: {title}")
                if title == "respiratory support":
                    insert_respiratory_support(cur, observation_pk_id, subtitle_data)
                    treatment_count += 1
                elif title == "sedation, analgesia, and neuromuscular blockade":
                    insert_sedation(cur, observation_pk_id, subtitle_data)
                    treatment_count += 1
                elif title == "inotropes and anti-hypertensives":
                    insert_inotropes(cur, observation_pk_id, subtitle_data)
                    treatment_count += 1
                elif title == "antimicrobials":
                    insert_antimicrobials(cur, observation_pk_id, subtitle_data)
                    treatment_count += 1
                elif title == "iv fluid":
                    insert_iv_fluid(cur, observation_pk_id, subtitle_data)
                    treatment_count += 1
                elif title == "feeds":
                    insert_feeds(cur, observation_pk_id, subtitle_data)
                    treatment_count += 1
                elif title == "other medications":
                    insert_other_medications(cur, observation_pk_id, subtitle_data)
                    treatment_count += 1
                # --- MODIFIED PART: Call insert_supportive_care ---
                elif title == "supportive care":
                    insert_supportive_care(cur, observation_pk_id, subtitle_data)
                    treatment_count += 1
                # --- END MODIFIED PART ---
            print(f"✓ Processed {treatment_count} treatment records")

        print("\n=== Committing Transaction ===")
        conn.commit()
        print("✓ All changes committed successfully!")
        print("\n=== Data Insertion Complete ===")
        print(f"Summary:")
        print(f"- Patient UUID: {patient_pk_uuid}")
        print(f"- Diagnosis ID: {diagnosis_pk_id}")
        print(f"- Observation ID: {observation_pk_id}")

    except psycopg2.Error as e:
        if conn: 
            print("\n=== Rolling Back Transaction ===")
            conn.rollback()
            print("✓ Transaction rolled back due to error")
        print(f"\n❌ Database error: {e}")
        if hasattr(cur, 'query') and cur.query: 
            print(f"Failed query: {cur.query}")
    except ValueError as ve:
        if conn: 
            print("\n=== Rolling Back Transaction ===")
            conn.rollback()
            print("✓ Transaction rolled back due to validation error")
        print(f"\n❌ Data validation error: {ve}")
    except Exception as e:
        if conn: 
            print("\n=== Rolling Back Transaction ===")
            conn.rollback()
            print("✓ Transaction rolled back due to unexpected error")
        print(f"\n❌ An unexpected error occurred: {e}")
    finally:
        if cur: 
            print("\n=== Closing Database Cursor ===")
            cur.close()
            print("✓ Cursor closed")
        if conn: 
            print("\n=== Closing Database Connection ===")
            conn.close()
            print("✓ Connection closed")

# --- Example Usage ---
if __name__ == "__main__":
    json_data_from_user = {
        'uuid': 'patient-app-uuid-001', 
        'Name': 'Duma Cat', 
        'Age_year': '4', 'Age_month': '5', 'Sex': 'Other', 'uhid': 'UHID-DUMA-001', 
        'Diagnosis': 'Acute Feline Boredom', 
        'Consultants': 'Dr. Whiskers',
        'each_entry_layout': { 
            'entry_1': {'title': 'Respiratory support', 'subtitles': {'subtitle_1': {'content': 'Oxygen PRN', 'rate': '2L/min', 'volume': 'N/A'}}}, 
            'entry_sc1': { # This entry will now be processed into the supportive_care table
                'title': 'Supportive care', 
                'subtitles': {
                    'subtitle_1': {
                        'content': 'Warm blanket and gentle petting', 
                        'rate': 'Continuous', # Example 'rate' for supportive care
                        'volume': 'As tolerated'  # Example 'volume'
                    }
                }
            },
            'entry_med1': {'title': 'Other Medications', 'subtitles': {'subtitle_1': {'content': 'Catnip 5mg', 'dose': '1 pinch', 'volume': 'PO'}}}
        }, 
        'each_table_row_layout': { 
            'row_1': {'row_header_name': 'Date', 'row_header_description': '2023-10-27'}, 
            'row_2': {'row_header_name': 'Time', 'row_header_description': '10:00 AM'}, 
            'row_3': {'row_header_name': 'Weight', 'row_header_description': '5 kg'}
        }
    }
    process_json_data(json_data_from_user)

    print("\n--- Processing another example (supportive care with only content) ---")
    json_data_supportive_only_content = {
        "uuid": "patient-app-uuid-002",
        "Name": "Patient SupportOnly",
        "uhid": "UHID-SUPPORT-002",
        "Diagnosis": "Mild Discomfort",
        "each_entry_layout": {
             "entry_sc2": {
                "title": "Supportive care",
                "subtitles": {"subtitle_1": {"content": "Rest and fluids"}} 
                # Rate and Volume will be NULL in the DB for this entry
            }
        },
        "each_table_row_layout": {
            "row_X1": { "row_header_name": "Date", "row_header_description": "2023-11-10" },
            "row_X2": { "row_header_name": "Time", "row_header_description": "09:00 AM" }
        }
    }
    process_json_data(json_data_supportive_only_content)